version: "3.6"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  app-gems:
    driver: local

services:
  nginx:
    image: nginx
    ports:
      - 80:30
      - 443:443
      - 3034:3034
    restart: on-failure
    volumes:
      - ./config/docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/docker-compose/server.crt:/etc/nginx/conf.d/server.crt
      - ./config/docker-compose/server.key:/etc/nginx/conf.d/server.key

  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    restart: on-failure
    environment:
      POSTGRES_USER: flurish
      POSTGRES_DB: flurish

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis:delegated
    restart: on-failure
    command: redis-server --appendonly yes

  cubeserver:
    image: gcr.io/omp-core/cubeserver:e0b678a8c4458eaddabe6486410e1fa31a7f0f4a
    ports:
      - 4001:4000
    restart: on-failure
    environment:
      NODE_ENV: development
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_NAME: flurish_development
      CUBEJS_DB_USER: flurish
      CUBEJS_API_SECRET: testdevelopmentapisecret
      REDIS_URL: redis://redis:6379/0
