---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web-assets
  name: web-assets
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"assets-backend-config"}}'
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    service: web
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: assets-ingress
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  tls:
    - secretName: assets.superpro.io-production
      hosts:
        - assets.superpro.io
  rules:
    - host: assets.superpro.io
      http:
        paths:
          - backend:
              serviceName: web-assets
              servicePort: 80
