/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A query submitted to the Superpro data server
 */
export interface WarehouseQuery {
  /**
   * A list of measures to query
   */
  measures: Measure[];
  /**
   * A list of dimensions to segment the query by
   */
  dimensions: Dimension[];
  /**
   * A list of model fields to order the query by
   */
  orderings?: Ordering[];
  /**
   * A list of model fields and values to filter the query by
   */
  filters?: Filter[];
}
export interface Measure {
  /**
   * Opaque identifier for this dimension used in references elsewhere
   */
  id: string;
  /**
   * The name of the root data model this measure is coming from.
   */
  model: string;
  /**
   * Which field of the data model this measure is.
   */
  field: string;
  /**
   * How to aggregate the underlying data
   */
  operator?: string;
}
export interface Dimension {
  /**
   * Opaque identifier for this dimension used in references elsewhere
   */
  id: string;
  /**
   * The name of the root data model this dimension is coming from.
   */
  model: string;
  /**
   * Which field of the data model this dimension is.
   */
  field: string;
  operator?:
    | "date_trunc_day"
    | "date_trunc_week"
    | "date_trunc_month"
    | "date_trunc_year"
    | "date_part_hour"
    | "date_part_day_of_month"
    | "date_part_day_of_week"
    | "date_part_week"
    | "date_part_month"
    | "date_part_year";
}
export interface Ordering {
  /**
   * The id of the measure or dimension to order by
   */
  id: string;
  direction: "asc" | "desc";
}
export interface Filter {
  /**
   * The id of the measure or dimension to filter by. Mutually exclusive with the field properties.
   */
  id?: string;
  /**
   * A field to filter on that isn't included in the returned values. Structured as a nested measure or dimension
   */
  field?: Measure | Dimension;
  operator: "equals" | "not_equals" | "greater_than" | "greater_than_or_equals" | "less_than" | "less_than_or_equals";
  values: (string | number)[];
}
