development:
  google_oauth_client_id: 276796846364-tj5re9m6q5spgbktnbr0puic79rkgjp1.apps.googleusercontent.com
  google_oauth_client_secret: nZBPPNiINZluFcy9rdH4PDMb
production:
  google_oauth_client_id: <%= ENV['ADMIN_GOOGLE_OAUTH_CLIENT_ID'] %>
  google_oauth_client_secret: <%= ENV['ADMIN_GOOGLE_OAUTH_CLIENT_SECRET'] %>
