development:
  api_url: https://cube.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
test:
  api_url: https://cube.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
integration_test:
  api_url: https://cube.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
production:
  api_url: https://cube.gapp.fun/cubejs-api/v1
  api_secret: <%= ENV['CUBEJS_API_SECRET'] %>
