development:
  # To hit a local development cubejs server, uncomment this line and restart the Rails backend server
  # api_url: https://cube.ggt.dev/cubejs-api/v1
  api_url: https://cube-docker-compose.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
test:
  api_url: https://cube-docker-compose.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
integration_test:
  api_url: https://cube-docker-compose.ggt.dev/cubejs-api/v1
  api_secret: testdevelopmentapisecret
production:
  api_url: https://cube.fluri.sh/cubejs-api/v1
  api_secret: <%= ENV['CUBEJS_API_SECRET'] %>
