development: &development
  google_oauth_client_id: 441963534992-nc47ocqf9po4qortnsdlv7rqn51u58un.apps.googleusercontent.com
  google_oauth_client_secret: fwwXsWvVz30h0koVlYbB7DE8
test:
  <<: *development
integration_test:
  <<: *development
production:
  google_oauth_client_id: 1056215503718-1laa3ndt9ar4dadc0q3qmc6ftn30nppe.apps.googleusercontent.com
  google_oauth_client_secret: <%= ENV['APP_GOOGLE_OAUTH_CLIENT_SECRET'] %>
