"Infrastructure::PeriodicSyncAllConnectionsJob":
  cron: "0 * * * *"

"Infrastructure::PeriodicSyncAllGlobalConnectionsJob":
  cron: "30 * * * *"

"Infrastructure::PeriodicShopifyScriptTagSetupJob":
  cron: "@daily"

"Infrastructure::TruncateSingerConnectionSyncAttemptsJob":
  cron: "@daily"
