development:
  # To hit a local development singer-importer server, uncomment this line and restart the Rails backend server
  # api_url: http://localhost:5000
  api_url: http://singer-importer-docker-compose.supo.dev:4002
  auth_token: testdevelopmentapisecret
test:
  # api_url: http://localhost:5000
  api_url: http://singer-importer-docker-compose.supo.dev:4002
  auth_token: testdevelopmentapisecret
integration_test:
  api_url: http://singer-importer-docker-compose.supo.dev:4002
  auth_token: testdevelopmentapisecret
production:
  api_url: https://singer-importer.superpro.io
  auth_token: <%= ENV['SINGER_IMPORTER_AUTH_TOKEN'] %>
